### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by carryfax** [carryfax/dgfrn#5]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by GataNina-Li** [comment]
Jjjjj

**Comment by carryfax** [comment]
okk

**Comment by carryfax** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Created a new connection
> 2. Closed & used saved credentials to log back in
> 3. Etc.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server?
> * What do your `connectOptions` look like?
> * Do you have multiple clients on the same IP?
> * Are you using a proxy?
> 
> **Additional context** Add any other context about the problem here.
